// <auto-generated />
using System;
using Assignment.ERD_Problems.Problem02;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment.Migrations.Context02Migrations
{
    [DbContext(typeof(Context02))]
    partial class Context02ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment.ERD_Problems.Problem02.Consultant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Consultants");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem02.Drug", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem02.DrugBrand", b =>
                {
                    b.Property<int>("DrugCode")
                        .HasColumnType("int");

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DrugCode", "BrandName");

                    b.ToTable("DrugBrands");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem02.Nurse", b =>
                {
                    b.Property<int>("NurseNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NurseNumber"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ward_Id")
                        .HasColumnType("int");

                    b.HasKey("NurseNumber");

                    b.HasIndex("Ward_Id");

                    b.ToTable("Nurses");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem02.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Consultant_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ward_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Consultant_Id");

                    b.HasIndex("Ward_Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem02.Patient_Consultant_Examine", b =>
                {
                    b.Property<int>("Patient_Id")
                        .HasColumnType("int");

                    b.Property<int>("Consultant_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Examine_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Patient_Id", "Consultant_Id", "Examine_Date");

                    b.HasIndex("Consultant_Id");

                    b.ToTable("Patient_Consultant_Examines");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem02.Patient_Nurse_Drug", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("NurseNumber")
                        .HasColumnType("int");

                    b.Property<int>("DrugCode")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId", "NurseNumber", "DrugCode", "Date", "Time");

                    b.HasIndex("DrugCode");

                    b.HasIndex("NurseNumber");

                    b.ToTable("Patient_Nurse_Drugs");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem02.Ward", b =>
                {
                    b.Property<int>("Ward_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ward_Id"));

                    b.Property<int>("Nurse_Number")
                        .HasColumnType("int");

                    b.Property<string>("Ward_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ward_Id");

                    b.HasIndex("Nurse_Number");

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem02.DrugBrand", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem02.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem02.Nurse", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem02.Ward", "Ward")
                        .WithMany()
                        .HasForeignKey("Ward_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem02.Patient", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem02.Consultant", "Consultant")
                        .WithMany()
                        .HasForeignKey("Consultant_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.ERD_Problems.Problem02.Ward", "Ward")
                        .WithMany()
                        .HasForeignKey("Ward_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultant");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem02.Patient_Consultant_Examine", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem02.Consultant", "Consultant")
                        .WithMany()
                        .HasForeignKey("Consultant_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.ERD_Problems.Problem02.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("Patient_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultant");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem02.Patient_Nurse_Drug", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem02.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.ERD_Problems.Problem02.Nurse", "Nurse")
                        .WithMany()
                        .HasForeignKey("NurseNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.ERD_Problems.Problem02.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("Nurse");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem02.Ward", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem02.Nurse", "Nurse")
                        .WithMany()
                        .HasForeignKey("Nurse_Number")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nurse");
                });
#pragma warning restore 612, 618
        }
    }
}
