// <auto-generated />
using System;
using Assignment.ERD_Problems.Problem03;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment.Migrations.Context03Migrations
{
    [DbContext(typeof(Context03))]
    partial class Context03ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment.ERD_Problems.Problem03.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlbumId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Musician_Id")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlbumId");

                    b.HasIndex("Musician_Id");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem03.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem03.Instrument", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Key")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem03.Musican_Instrument", b =>
                {
                    b.Property<int>("MusicianId")
                        .HasColumnType("int");

                    b.Property<string>("Instrument_Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MusicianId", "Instrument_Name");

                    b.HasIndex("Instrument_Name");

                    b.ToTable("Musican_Instruments");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem03.Musician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone_Number")
                        .HasColumnType("int");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Musicians");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem03.Song", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Album_Id")
                        .HasColumnType("int");

                    b.Property<int>("Author_Id")
                        .HasColumnType("int");

                    b.HasKey("Title");

                    b.HasIndex("Album_Id");

                    b.HasIndex("Author_Id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem03.Song_Musican", b =>
                {
                    b.Property<string>("Song_Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MusicianId")
                        .HasColumnType("int");

                    b.HasKey("Song_Title", "MusicianId");

                    b.HasIndex("MusicianId");

                    b.ToTable("Song_Musicans");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem03.Album", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem03.Musician", "Musician")
                        .WithMany("Albums")
                        .HasForeignKey("Musician_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musician");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem03.Musican_Instrument", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem03.Instrument", "Instrument")
                        .WithMany("MusicianInstruments")
                        .HasForeignKey("Instrument_Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.ERD_Problems.Problem03.Musician", "Musician")
                        .WithMany("MusicianInstruments")
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Musician");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem03.Song", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem03.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("Album_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.ERD_Problems.Problem03.Author", "Author")
                        .WithMany("Songs")
                        .HasForeignKey("Author_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem03.Song_Musican", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem03.Musician", "Musician")
                        .WithMany("Song_Musicans")
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.ERD_Problems.Problem03.Song", "Song")
                        .WithMany("Song_Musicans")
                        .HasForeignKey("Song_Title")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musician");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem03.Album", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem03.Author", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem03.Instrument", b =>
                {
                    b.Navigation("MusicianInstruments");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem03.Musician", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("MusicianInstruments");

                    b.Navigation("Song_Musicans");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem03.Song", b =>
                {
                    b.Navigation("Song_Musicans");
                });
#pragma warning restore 612, 618
        }
    }
}
