// <auto-generated />
using System;
using Assignment.ERD_Problems.Problem01;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment.Migrations.Context01Migrations
{
    [DbContext(typeof(Context01))]
    partial class Context01ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment.ERD_Problems.Problem01.AirCraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Airline_Id")
                        .HasColumnType("int");

                    b.Property<int>("Assistant_Pilot_Id")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Hostess01_Id")
                        .HasColumnType("int");

                    b.Property<int>("Hostess02_Id")
                        .HasColumnType("int");

                    b.Property<int>("Major_Pilot_Id")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Airline_Id");

                    b.HasIndex("Assistant_Pilot_Id");

                    b.HasIndex("Hostess01_Id");

                    b.HasIndex("Hostess02_Id");

                    b.HasIndex("Major_Pilot_Id");

                    b.ToTable("AirCrafts");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem01.AirCraft_Route", b =>
                {
                    b.Property<int>("AirCraft_Id")
                        .HasColumnType("int");

                    b.Property<int>("Route_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Number_of_Passengers")
                        .HasColumnType("int");

                    b.Property<int>("Price_per_Passenger")
                        .HasColumnType("int");

                    b.HasKey("AirCraft_Id", "Route_Id");

                    b.HasIndex("Route_Id");

                    b.ToTable("AirCraft_Routes");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem01.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Person")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem01.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Airline_Id")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Airline_Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem01.Hostess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Airline_Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Airline_Id");

                    b.ToTable("Hostesses");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem01.Phones", b =>
                {
                    b.Property<int>("Airline_Id")
                        .HasColumnType("int");

                    b.Property<int>("Phone_Number")
                        .HasColumnType("int");

                    b.HasKey("Airline_Id", "Phone_Number");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem01.Pilot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Airline_Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Airline_Id");

                    b.ToTable("Pilots");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem01.Qualifications", b =>
                {
                    b.Property<int>("Employee_Id")
                        .HasColumnType("int");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Employee_Id", "Qualification");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem01.Route", b =>
                {
                    b.Property<int>("Route_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Route_Id"));

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Route_Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem01.Transactions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Airline_Id")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Airline_Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem01.AirCraft", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem01.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("Airline_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.ERD_Problems.Problem01.Pilot", "Assistant_Pilot")
                        .WithMany()
                        .HasForeignKey("Assistant_Pilot_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.ERD_Problems.Problem01.Hostess", "Hostess01")
                        .WithMany()
                        .HasForeignKey("Hostess01_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.ERD_Problems.Problem01.Hostess", "Hostess02")
                        .WithMany()
                        .HasForeignKey("Hostess02_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.ERD_Problems.Problem01.Pilot", "Major_Pilot")
                        .WithMany()
                        .HasForeignKey("Major_Pilot_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("Assistant_Pilot");

                    b.Navigation("Hostess01");

                    b.Navigation("Hostess02");

                    b.Navigation("Major_Pilot");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem01.AirCraft_Route", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem01.AirCraft", "AirCraft")
                        .WithMany()
                        .HasForeignKey("AirCraft_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.ERD_Problems.Problem01.Route", "Route")
                        .WithMany()
                        .HasForeignKey("Route_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirCraft");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem01.Employee", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem01.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("Airline_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem01.Hostess", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem01.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("Airline_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem01.Phones", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem01.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("Airline_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem01.Pilot", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem01.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("Airline_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem01.Qualifications", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem01.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem01.Transactions", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem01.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("Airline_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });
#pragma warning restore 612, 618
        }
    }
}
