// <auto-generated />
using Assignment.ERD_Problems.Problem04;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment.Migrations.Context04Migrations
{
    [DbContext(typeof(Context04))]
    partial class Context04ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment.ERD_Problems.Problem04.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalesOfficeNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalesOfficeNumber");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem04.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem04.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("SalesOfficeNubmer")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SalesOfficeNubmer");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem04.Property_Owner", b =>
                {
                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Percent")
                        .HasColumnType("int");

                    b.HasKey("PropertyId", "OwnerId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Property_Owners");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem04.Sales_Office", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Number");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Sales_Offices");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem04.Employee", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem04.Sales_Office", "SalesOffice")
                        .WithMany("Employees")
                        .HasForeignKey("SalesOfficeNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesOffice");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem04.Property", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem04.Sales_Office", "SalesOffice")
                        .WithMany("Properties")
                        .HasForeignKey("SalesOfficeNubmer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesOffice");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem04.Property_Owner", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem04.Owner", "Owner")
                        .WithMany("PropertyOwners")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.ERD_Problems.Problem04.Property", "Property")
                        .WithMany("PropertyOwners")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem04.Sales_Office", b =>
                {
                    b.HasOne("Assignment.ERD_Problems.Problem04.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem04.Owner", b =>
                {
                    b.Navigation("PropertyOwners");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem04.Property", b =>
                {
                    b.Navigation("PropertyOwners");
                });

            modelBuilder.Entity("Assignment.ERD_Problems.Problem04.Sales_Office", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
